# Generated by Django 5.2.6 on 2025-09-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_created_at_dojo_updated_at_ninja_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='description for dojo'),
            preserve_default=False,
        ),
    ]
